services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: seblm-database-password
      POSTGRES_USER: seblm-meals
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
  application:
    build: target/docker/stage
    image: seblm/seblm-meals
    depends_on:
      - database
    environment:
      APPLICATION_SECRET: ziN0JiGEzE6FvUBddNcEttAC/WdabutXXblfzusCQSs=
      APPLICATION_UPDATE_DB:
      POSTGRESQL_ADDON_USER: seblm-meals
      POSTGRESQL_ADDON_PASSWORD: seblm-database-password
      POSTGRESQL_ADDON_HOST: database
      POSTGRESQL_ADDON_DB: seblm-meals
    ports:
      - "9000:9000"
volumes:
  data:
