name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.18'
          cache: 'yarn'
          cache-dependency-path: 'frontend'
      - run: yarn && yarn build
        working-directory: frontend
