name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt/boot
          key: ${{ runner.os }}-sbt-${{ hashFiles('project/build.properties') }}
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier/v1
          key: ${{ runner.os }}-sbt-${{ hashFiles('build.sbt') }}
      - name: Check Scalafmt
        continue-on-error: true
        run: sbt scalafmtCheckAll
      - name: Run tests
        run: sbt test
